name: first

on: workflow_dispatch

permissions:
  actions: write

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Run
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh --version
        gh workflow run second.yml